spring:
  application:
    name: activityservice
  management:
    endpoints:
      web:
        exposure:
          include: health, info
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082