spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/ai_fitness_recommendation
      database: ai_fitness_recommendation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
